const districts = [
    "EAST_DISTRICT",
    "NORTH_DISTRICT",
    "SOUTH_DISTRICT",
    "CHITUNGWIZA_DISTRICT",
    "CHINHOYI_DISTRICT",
    "BINDURA_DISTRICT",
    "KADOMA_DISTRICT",
    "MARONDERA_DISTRICT",
    "HARARE_ENVIRONS",
    "GWERU_DISTRICT",
    "KWEKWE_DISTRICT",
    "MUTARE_DISTRICT",
    "MANICALAND_DISTRICT",
    "MASVINGO_DISTRICT",
    "BULAWAYO_RURAL_DISTRICT",
    "BYO_WEST_DISTRICT",
    "BYO_EAST_DISTRICT"
]

export default districts